"""Updating tables on laptop to match desktop

Revision ID: 2a097046a1bd
Revises: 22e172525b7b
Create Date: 2023-12-16 09:57:51.058688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a097046a1bd'
down_revision: Union[str, None] = '22e172525b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('amenities', sa.String(), nullable=True),
    sa.Column('policies', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_table('booking_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('policy_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_policies_id'), 'booking_policies', ['id'], unique=False)
    op.create_index(op.f('ix_booking_policies_name'), 'booking_policies', ['name'], unique=False)
    op.create_table('meal_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_options_id'), 'meal_options', ['id'], unique=False)
    op.create_index(op.f('ix_meal_options_name'), 'meal_options', ['name'], unique=False)
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_types_id'), 'room_types', ['id'], unique=False)
    op.create_index(op.f('ix_room_types_name'), 'room_types', ['name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('hotel_foc_slots', sa.String(), nullable=True),
    sa.Column('diving_foc_slots', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=False)
    op.create_table('special_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_offers_id'), 'special_offers', ['id'], unique=False)
    op.create_index(op.f('ix_special_offers_name'), 'special_offers', ['name'], unique=False)
    op.create_table('diving_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diving_packages_id'), 'diving_packages', ['id'], unique=False)
    op.create_index(op.f('ix_diving_packages_name'), 'diving_packages', ['name'], unique=False)
    op.create_table('occupancy_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('occupancy_type', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_rates_id'), 'occupancy_rates', ['id'], unique=False)
    op.create_table('group_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('travel_agent', sa.String(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.Column('diving_package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diving_package_id'], ['diving_packages.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_contracts_group_name'), 'group_contracts', ['group_name'], unique=False)
    op.create_index(op.f('ix_group_contracts_id'), 'group_contracts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_contracts_id'), table_name='group_contracts')
    op.drop_index(op.f('ix_group_contracts_group_name'), table_name='group_contracts')
    op.drop_table('group_contracts')
    op.drop_index(op.f('ix_occupancy_rates_id'), table_name='occupancy_rates')
    op.drop_table('occupancy_rates')
    op.drop_index(op.f('ix_diving_packages_name'), table_name='diving_packages')
    op.drop_index(op.f('ix_diving_packages_id'), table_name='diving_packages')
    op.drop_table('diving_packages')
    op.drop_index(op.f('ix_special_offers_name'), table_name='special_offers')
    op.drop_index(op.f('ix_special_offers_id'), table_name='special_offers')
    op.drop_table('special_offers')
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_room_types_name'), table_name='room_types')
    op.drop_index(op.f('ix_room_types_id'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_meal_options_name'), table_name='meal_options')
    op.drop_index(op.f('ix_meal_options_id'), table_name='meal_options')
    op.drop_table('meal_options')
    op.drop_index(op.f('ix_booking_policies_name'), table_name='booking_policies')
    op.drop_index(op.f('ix_booking_policies_id'), table_name='booking_policies')
    op.drop_table('booking_policies')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
